kind: 
name: legacy

steps:
- name: install
  image: blcoccaro/to-deploy:v2
  volumes:
  - name: wl
    path: /tmp/host
  commands:
  - pwd
  
volumes:
- name: wl
  host:
    path: /hd/www/unique

trigger:
  branch:
  - master
  event:
  - push
  - promote
