kind: 
name: legacy

steps:
- name: install
  image: blcoccaro/to-deploy:v2
  volumes:
  - name: wl
    path: /tmp/host
  commands:
  - rsync -vr /tmp/host/legacy/ /tmp/host/bk/legacy
  - cd comprar
  - gulp sass
  - cd ..
  - rsync -vrR --exclude='.git' * /tmp/host/legacy
  - rsync -vrR .htaccess /tmp/host/legacy
  - chmod -R 777 /tmp/host/legacy/
  
volumes:
- name: wl
  host:
    path: /var/www/unique

trigger:
  branch:
  - master
  event:
  - push