<?php

require_once('../settings/settings.php');
require_once('../settings/functions.php');
$mainConnection = mainConnection();
$conn = getConnection($_POST['cboTeatro']);
$_POST['cboSala'] = $_POST['cboSala'] == 'TODOS' ? '' : $_POST['cboSala'];
$query = "WITH RESULTADO
AS (
	SELECT 
		COUNT(S.INDICE) AS QTDINGTOTAL,
		(SELECT COUNT(C.INDICE) FROM TABCONTROLESEQVENDA C WHERE C.CODAPRESENTACAO = A.CODAPRESENTACAO AND C.STATUSINGRESSO = 'U') AS QTDINGLIDOS,
		(SELECT COUNT(C.INDICE) FROM TABCONTROLESEQVENDA C WHERE C.CODAPRESENTACAO = A.CODAPRESENTACAO AND C.STATUSINGRESSO = 'L') AS QTDINGLIVRE,
		SUM(CASE WHEN B.PERDESCONTO < 100 THEN 1 ELSE 0 END) AS QTDINGPAGANTE,
		SUM(CASE WHEN B.PERDESCONTO < 100 THEN 0 ELSE 1 END) AS QTDINGCONVITE,		
		(SELECT MIN(C.DATHRENTRADA) FROM TABCONTROLESEQVENDA C WHERE C.CODAPRESENTACAO = A.CODAPRESENTACAO) AS HRLEITURAINI,
		(SELECT MAX(C.DATHRENTRADA) FROM TABCONTROLESEQVENDA C WHERE C.CODAPRESENTACAO = A.CODAPRESENTACAO) AS HRLEITURAFIM,
		(SELECT SUM(VALPAGTO) 
		FROM TABLANCAMENTO L
		WHERE CODAPRESENTACAO = A.CODAPRESENTACAO 
			AND NOT EXISTS (SELECT 1 FROM TABLANCAMENTO LE 
							WHERE LE.NUMLANCAMENTO = L.NUMLANCAMENTO
							AND LE.CODAPRESENTACAO = L.CODAPRESENTACAO
							AND LE.CODTIPBILHETE = L.CODTIPBILHETE
							AND LE.CODTIPLANCAMENTO = 2
							AND LE.INDICE = L.INDICE) ) AS VALINGTOTAL
	FROM TABLUGSALA S
	INNER JOIN TABAPRESENTACAO A
		ON A.CODAPRESENTACAO = S.CODAPRESENTACAO
	INNER JOIN TABTIPBILHETE B ON B.CODTIPBILHETE = S.CODTIPBILHETE
	WHERE A.DATAPRESENTACAO = CONVERT(DATETIME, ?, 112) 
		AND A.HORSESSAO = ? AND A.CODPECA = ? AND S.STACADEIRA = 'V'
	GROUP BY 
		A.CODAPRESENTACAO 
	)
SELECT DISTINCT
	SUM(QTDINGTOTAL) AS QTDINGTOTAL,
	SUM(QTDINGLIDOS) AS QTDINGLIDOS,
	SUM(QTDINGLIVRE) AS QTDINGLIVRE, 
	SUM(QTDINGPAGANTE) AS QTDINGPAGANTE,
	SUM(QTDINGCONVITE) AS QTDINGCONVITE,
        RIGHT('00' + CONVERT(VARCHAR, DATEDIFF(HOUR, MIN(HRLEITURAINI), MAX(HRLEITURAFIM)) % 24), 2) + ' HORAS E ' 
	+ RIGHT('00' + CONVERT(VARCHAR, DATEDIFF(MINUTE, MIN(HRLEITURAINI), MAX(HRLEITURAFIM)) % 60), 2) + ' MINUTOS E ' 
	+ RIGHT('00' + CONVERT(VARCHAR, DATEDIFF(SECOND, MIN(HRLEITURAINI), MAX(HRLEITURAFIM)) % 60), 2) + ' SEGUNDOS' AS HRLEITURADURACAO,
	CONVERT(VARCHAR(10) , MIN(HRLEITURAINI), 103) +' - '+ CONVERT(VARCHAR(8) , MIN(HRLEITURAINI), 114) AS HRLEITURAINI,
	CONVERT(VARCHAR(10), MAX(HRLEITURAFIM), 103) +' - '+ CONVERT(VARCHAR(8), MAX(HRLEITURAFIM), 114) AS HRLEITURAFIM,
	SUM(VALINGTOTAL) AS VALINGTOTAL
FROM RESULTADO";
    $params = array($_POST['cboApresentacao'], $_POST['cboHorario'], $_POST['cboPeca']);
    $result = executeSQL($conn, $query, $params);

    if (hasRows($result)) {
        while ($rs = fetchResult($result)) {
            if($rs['QTDINGTOTAL'] == NULL){
                $json = array("resultado" => "Nenhum acesso encontrado.");
            }else{
				$query2 = "SELECT STUFF ((
						SELECT ',' + CONVERT(VARCHAR, CODAPRESENTACAO)
						FROM TABAPRESENTACAO
						WHERE CODPECA = ? AND convert(varchar(10), DATAPRESENTACAO, 112) = ? AND HORSESSAO = ?
						FOR XML PATH('')
						),1,1,'')";
				$params2 = array($_POST['cboPeca'], $_POST['cboApresentacao'], $_POST['cboHorario']);
				$rs2 = executeSQL($conn, $query2, $params2, true);

				$query3 = "SELECT isnull(COUNT(DISTINCT(B.CODBAR)), 0) as 'in', isnull(SUM(CASE WHEN B.DATHRSAIDA IS NOT NULL THEN 1 ELSE 0 END), 0) as 'out'
							FROM TABCONTROLESEQVENDA A
							INNER JOIN TABCONTROLESEQVENDA B ON B.CODAPRESENTACAO = A.CODAPRESENTACAO AND B.INDICE = A.INDICE AND B.STATUSINGRESSO = A.STATUSINGRESSO
							WHERE A.CODAPRESENTACAO in ({$rs2[0]}) AND A.STATUSINGRESSO = 'U'";

				$params3 = array($rs2['CODAPRESENTACAO']);
				$rs3 = executeSQL($conn, $query3, $params3, true);

				$rs3['on'] = $rs3['in'] - $rs3['out'];
				
                $json = array(
                    "QTDINGTOTAL" => $rs['QTDINGTOTAL'],
                    "QTDINGLIDOS" => $rs['QTDINGLIDOS'],
                    "QTDINGLIVRE" => $rs['QTDINGLIVRE'],
                    "QTDINGPAGANTE" => $rs['QTDINGPAGANTE'],
                    "QTDINGCONVITE" => $rs['QTDINGCONVITE'],
                    "VALINGTOTAL" => "R$ ". number_format($rs['VALINGTOTAL'], 2, ',', '.'),
                    "HRLEITURADURACAO" => $rs['HRLEITURADURACAO'],
                    "HRLEITURAINI" => $rs['HRLEITURAINI'],
                    "HRLEITURAFIM" => $rs['HRLEITURAFIM'],
					"CHECKIN" => $rs3['in'],
					"CHECKON" => $rs3['on'],
					"CHECKOUT" => $rs3['out']
                );
            }
        }
    } else {
        $json = array("resultado" => "Nenhum acesso encontrado.");
    }
    echo json_encode($json);

?>