<?php
require_once($_SERVER['DOCUMENT_ROOT']."/settings/multisite/unique.php");
?>
<div class="centraliza hidden" id="termos_de_uso">
	<div class="fechar"></div>
	<h2>Termos de uso</h2>
	<p>Esta página pode conter informações proprietárias e protegidas por direito autoral, que devem ser tratadas como tal acordo. A informação neste Website pode conter incorreções técnicas ou erros tipográficos, e pode ser alterada ou atualizada sem aviso prévio. A <?php echo multiSite_getName(); ?> pode, também, fazer melhorias e/ou alterações nos serviços e/ou nos produtos aqui descritos a qualquer momento, sem aviso prévio. </p>

	<p>Quaisquer comentários ou materiais enviados a <?php echo multiSite_getName(); ?>, incluindo dados de "feedback", como perguntas, comentários, sugestões, ou qualquer outro material do gênero contido em tais documentos (chamados coletivamente de "feedback") serão considerados não-confidenciais. A <?php echo multiSite_getName(); ?> não terá nenhuma obrigação relativa a tal "feedback", e terá liberdade para reproduzir, usar, divulgar, exibir, transformar, criar peças derivadas e distribuir o "feedback" a terceiros, sem limitação alguma.</p>

	<p>Além disto, a <?php echo multiSite_getName(); ?> terá liberdade para usar quaisquer idéias, conceitos, know-how ou técnicas contidas nos "feedbacks" para qualquer finalidade, seja ela qual for, incluindo - mas não limitado a - desenvolvimento, fabricação e marketing de produtos, incorporando tal "feedback". </p>

	<p>A <?php echo multiSite_getName(); ?> não faz nenhuma declaração de nenhuma espécie quanto a qualquer outro Website que possa ser acessado a partir deste. Ao acessar um Website que não a <?php echo multiSite_getName(); ?>, entenda que ele é totalmente independente da <?php echo multiSite_getName(); ?> e que a <?php echo multiSite_getName(); ?> não tem nenhum controle sobre o conteúdo daquele Website. Além disto, um link a um site que não a <?php echo multiSite_getName(); ?> não significa que a <?php echo multiSite_getName(); ?> endossa ou aceita qualquer responsabilidade pelo conteúdo, ou pelo uso daquele Website. Cabe ao usuário tomar as precauções devidas para garantir que qualquer item selecionado para seu uso esteja livre de coisas como vírus, larvas, cavalos de tróia e outros itens de natureza destrutiva. </p>

	<p>Se o usuário enviar uma mensagem através do "Forum <?php echo multiSite_getName(); ?>" ou outra qualquer, o usuário é o único responsável pelo conteúdo de tal mensagem. A <?php echo multiSite_getName(); ?> não aceita nenhuma responsabilidade por quaisquer mensagens enviadas pelos usuários. Além disso, o usuário não deve enviar nenhuma mensagem que possa ser considerada ofensiva por qualquer pessoa ou grupo. Qualquer mensagem enviada será considerada "feedback", conforme definido acima.</p>
</div>
<div class="centraliza hidden" id="politica_de_privacidade">
	<div class="fechar"></div>
	<h2>Política de Privacidade</h2>
	<p class="destaque">Nós respeitamos a sua privacidade A <?php echo multiSite_getName(); ?> sabe que a sua privacidade é muito importante. Por favor, tome um minuto do seu tempo para ler e entender a nossa "Política de Privacidade", para que você entenda como tratamos a sua informação pessoal. Se você tiver alguma pergunta sobre esta política, sobre as práticas deste site ou a sua relação com a <?php echo multiSite_getName(); ?>, envie um e-mail para <a href="<?php echo "mailto:" . multiSite_getEmail("sac"); ?>"><?php echo multiSite_getEmail("sac"); ?></a></p>

	<h3>Padrão mundial</h3>
	<p>Devido à importância que o assunto privacidade exige, a <?php echo multiSite_getName(); ?> preparou o seu manual baseado nos princípios utilizados pelos maiores e mais importantes sites de todo o mundo, usando como base o TRUSTe.org , organização que tem como objetivo promover as normas de confidencialidade de dados e privacidade no mundo digital.</p>

	<h3>Livre navegação</h3>
	<p>Em geral, você poderá navegar por este endereço Web <?php echo multiSite_getURI("URI_SSL"); ?> sem ter de declarar quem você é ou revelar qualquer informação a seu respeito. Haverá ocasiões, no entanto, em que poderá ser necessário uma identificação e a obtenção de seus dados pessoais, tais como seu nome, CPF, endereço, telefone, etc. Nossa intenção é lhe comunicar antes de coletar informações a seu respeito na Internet.</p>

	<h3>Pesquisas e enquetes</h3>
	<p>Ao se cadastrar e/ou participar de uma pesquisa na <?php echo multiSite_getName(); ?>, você responde algumas informações pessoais e sobre seus interesses. Nós usamos essas informações para entender melhor o seu gosto e adaptar o site da melhor forma possível para você. Além do que estipula esta "Política de Privacidade", nós não revelamos, alugamos ou vendemos sua informação pessoal para outros, sem sua aprovação ou conhecimento. Nós podemos utilizar alguns serviços provindos de outras companhias para nossos usuários. Em alguns casos, você terá que cadastrar-se conjuntamente com este parceiro para poder receber seus serviços. Através do cadastro conjunto, você estará dando sua informação pessoal também para esta outra empresa. Você, então, poderá receber informações sobre serviços e atualizações deste parceiro.</p>

	<h3>E-mail de atualizações e notícias</h3>
	<p>Algumas vezes, a <?php echo multiSite_getName(); ?> envia e-mails de atualização com as novidades e outros serviços que o nosso site oferece para os usuários. Nós também poderemos enviar e-mails sobre novos produtos, companhias ou eventos que possam ser do seu interesse. Você poderá cancelar este serviço simplesmente seguindo as instruções contidas no e-mail. Em promoções  nós poderemos solicitar, entre outras ocasiões, alguns dados pessoais identificáveis, para que você possa participar de sorteios, concursos ou promoções realizadas pela <?php echo multiSite_getName(); ?> ou por parceiros. Salas de Bate-Papo e Fóruns Embora a <?php echo multiSite_getName(); ?> tenha o direito de monitorar as salas de Bate Papo e os Fóruns, não será possível fazê-lo permanentemente. Lembre-se de que, se você divulgar alguma informação pessoal nas salas de Bate Papo ou nos fóruns, esta poderá ser usada por outras pessoas.</p>

	<h3>Direito autoral e autoridades legais</h3>
	<p>Aviso: as imagens contidas neste site são protegidas pela lei de direito autoral. nº 5988 de 14/02/73. A cópia indevida ou a duplicação parcial ou total destas peças sofrerá pena de acordo com a lei que rege os direitos do autor. Nós poderemos compartilhar as informações dos nossos usuários com as autoridades do governo, quando tivermos alguma razão para acreditar que alguém está causando danos ou interferindo com nossos direitos ou propriedade intelectual, com outros usuários da <?php echo multiSite_getName(); ?> ou com qualquer outra pessoa que possa sair prejudicado por estas atividades.</p>

	<h3>Cookies</h3>
	<p>Tentamos oferecer para você serviços e produtos de acordo com seus interesses. Para isso, utilizamos os "cookies" para guardar ou traçar informação sobre você. Um "cookie" é uma pequena quantidade de dados enviado ao seu browser pelo servidor Web, que é guardado no "hard disk" do seu computador. Nós utilizamos os "cookies" para: acessar sua informação na <?php echo multiSite_getName(); ?> (que está na base de dados dos nossos computadores), oferecer um serviço personalizado; estimar o tamanho da nossa audiência para os nossos anunciantes; saber o número de visitas em nossas promoções, sorteios e concursos; e identificar quais áreas do nosso site você visitou. Nós analisamos esses dados para melhor entender nossos usuários. Esta informação nos permite oferecer um serviço que coincidirá melhor com seus interesses. Nós também mostramos uma análise dos nossos usuários (como um grupo) para os nossos potenciais parceiros, anunciantes e terceiros.</p>

	<h3>Acesso a outros sites através da <?php echo multiSite_getName(); ?></h3>
	<p>Você deve saber que, quando estiver na <?php echo multiSite_getName(); ?>, terá a oportunidade de visitar outros sites não-operados pela <?php echo multiSite_getName(); ?>. Estes sites, dos quais alguns são anunciantes da <?php echo multiSite_getName(); ?>, poderão obter informação pessoal identificável sobre você. A <?php echo multiSite_getName(); ?> não controla os sites operados por outros e não se responsabiliza pelo uso de informações destes sites. Esta declaração de privacidade não se aplica para estes outros sites ou anunciantes.</p>

	<h3>Uso de conteúdo dos colaboradores</h3>
	<p>A <?php echo multiSite_getName(); ?> é uma comunidade virtual com o objetivo de divulgar o teatro nacional e permitir o livre intercâmbio de ideias e opiniões entre seus usuários. A <?php echo multiSite_getName(); ?> não se responsabiliza por opiniões, comentários, artigos, títulos e/ou espetáculos publicados por colaboradores, moderadores, usuários e entrevistados que, de alguma forma, através de imagem e/ou conteúdo, possam causar ofensas, perdas e danos, pois não representam a opinião dos nossos editores.</p>
</div>